<footer class="bg-light-gray color-dark-gray vertical-padding-20">

    <div class="row column">
		&copy; 2017 F&amp;S Logistics, Inc.  All Rights Reserved.
		<span class="pull-right">
		<a href="https://www.facebook.com/GOFSL/" target="_blank"><i class="fa fa-facebook-official fa-lg"></i></a>
		</span>
    </div>

</footer>

<div id="facebook-float" class="animated rubberBand slide-out">
	Follow FSL <a href="https://www.facebook.com/GOFSL/" target="_blank"><i class="fa fa-facebook-official fa-lg"></i></a>
</div>