<aside class="section-nav show-for-large" id="section-nav">
    <nav itemscope="itemscope" itemtype="http://schema.org/SiteNavigationElement">
        <ul class="nav-docurrent">
            <li><a href="/about/mission.shtml" itemprop="url"><span itemprop="name">Our Mission</span></a></li>
            <li><a href="/about/green.shtml" itemprop="url" class=""><span itemprop="name">Green Initiatives</span></a></li>            
			<li><a href="/about/careers.shtml" itemprop="url" class=""><span itemprop="name">Careers</span></a></li> 
        </ul>
    </nav>
</aside>