<aside class="section-nav show-for-large" id="section-nav">
    <nav itemscope="itemscope" itemtype="http://schema.org/SiteNavigationElement">
        <ul class="nav-docurrent">
            <li><a href="/carriers.shtml" itemprop="url"><span itemprop="name">More Information</span></a></li>
            <li><a href="https://www.drivefs.com/machform/view.php?id=12615" target="_blank" itemprop="url"><span itemprop="name">Registration</span></a></li>  
        </ul>
    </nav>
</aside>