<aside class="section-nav show-for-large" id="section-nav">
    <nav itemscope="itemscope" itemtype="http://schema.org/SiteNavigationElement">
        <ul class="nav-docurrent">
            <li><a href="/logistics/index.shtml" itemprop="url" class=""><span itemprop="name">Logistics</span></a></li>
            <li><a href="/logistics/available-loads.shtml" itemprop="url"><span itemprop="name">Available Loads</span></a></li>
            <li><a href="/files/fsl-carrier-packet.pdf" itemprop="url" class=""><span itemprop="name">Carrier Packet</span></a></li>            
        </ul>
    </nav>
</aside>