<div id="offCanvas" class="off-canvas position-right" data-off-canvas>
    <nav class="mobile off-canvas-list" role="navigation" aria-label="Mobile navigation" itemscope="itemscope" itemtype="http://schema.org/SiteNavigationElement">
        <ul class="nav-docurrent">
            <li><a href="/" itemprop="url" tabindex="1"><span itemprop="name">Home</span></a></li>
            <li class="has-children">
                <a href="/soon.shtml" data-path="about" itemprop="url" tabindex="1"><span itemprop="name">About F&amp;S</span></a>
                <a href="#" class="more" tabindex="1">More About</a>
                <ul class="children">
            <li><a href="/soon.shtml" itemprop="url" tabindex="1"><span itemprop="name">Mission Statement</span></a></li>
            <li><a href="/about/team.shtml" itemprop="url" tabindex="1"><span itemprop="name">Meet the Team</span></a></li>
            <li><a href="/soon.shtml" itemprop="url" tabindex="1"><span itemprop="name">Careers</span></a></li>
        </ul>
            </li>
            <li class="has-children"><a href="/carriers.shtml" data-path="carriers" itemprop="url" tabindex="1"><span itemprop="name">Carriers</span></a>
			<a href="#" class="more" tabindex="1">More Carriers</a>
                <ul class="children">
                    <li><a href="/carriers.shtml" itemprop="url"><span itemprop="name">More Information</span></a></li>
					<li><a href="https://www.drivefs.com/machform/view.php?id=12615" itemprop="url" target="_blank"><span itemprop="name">Registration - "Grow with FSL"</span></a></li>
                </ul>
			</li>
            <li class="has-children"><a href="/soon.shtml" data-path="services" itemprop="url" tabindex="1"><span itemprop="name">Services</span></a>
			<a href="#" class="more" tabindex="1">More Services</a>
                <ul class="children">
                    <li><a href="/soon.shtml" itemprop="url"><span itemprop="name">Request a Quote</span></a></li>
					<li><a href="/services/pickup.shtml" itemprop="url"><span itemprop="name">FCA Supplier Pick-up Request</span></a></li>
					<li><a href="/soon.shtml" itemprop="url"><span itemprop="name">3PL</span></a></li>
					<li><a href="/soon.shtml" itemprop="url"><span itemprop="name">Brokerage</span></a></li>
					<li><a href="/soon.shtml" itemprop="url"><span itemprop="name">Supply Chain Consultation</span></a></li>
                </ul>
			</li>
            <li><a href="/loads/" data-path="loads" itemprop="url" tabindex="1"><i class="fa fa-map-signs color-orange"></i>&nbsp;<span itemprop="name">Available Loads</span></a></li>
            <li><a href="/contact.shtml" data-path="contact" itemprop="url" tabindex="1"><span itemprop="name">Contact</span></a></li>
        </ul>
    </nav>
    <button class="close-button" aria-label="Close menu" type="button" data-close>
        <span aria-hidden="true">&times;</span>
    </button>
</div>  